---
- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Install openjdk-17-jdk
  become: true
  apt:
    name: openjdk-17-jdk
    state: latest

- name: update-java-alternatives
  become: true
  alternatives:
    name: java
    path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
