---
- hosts: localhost
  roles:
    - docker
  vars_prompt:
    - name: container_version
      prompt: 'Choose your container.io version'
      default: '1.7.27-1'
      private: no
    - name: docker_version
      prompt: 'Choose your Docker version'
      default: '28.3.3-1'
      private: no
