name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check docker version
      run: docker version
    - name: Build Docker image
      run: |
        docker build -q -t ansible:test .
        docker images
    - name: Start Docker container
      run: docker run --name containertest -d -w /home/jhipster/app/playbooks/ ansible:test
    - name: Display ansible version
      run: docker exec -t containertest ansible --version
    - name: tools
      run: |
        docker exec -t containertest ansible-playbook tools.yml -e ansible_become_pass=jhipster
        docker exec -t containertest vim --version
        docker exec -t containertest curl --version
        docker exec -t containertest wget --version
    - name: git
      run: |
        docker exec -t containertest ansible-playbook git.yml -e ansible_become_pass=jhipster -e 'git_username="Firstname Lastname"' -e git_email=yourmail@localhost
        docker exec -t containertest git version
    - name: zsh
      run: |
        docker exec -t containertest ansible-playbook zsh.yml -e ansible_become_pass=jhipster
        docker exec -t containertest zsh --version
    - name: openjdk17
      run: |
        docker exec -t containertest ansible-playbook openjdk17.yml -e ansible_become_pass=jhipster
        docker exec -t containertest java -version
        docker exec -t containertest javac -version
    - name: Maven
      run: |
        docker exec -t containertest ansible-playbook maven.yml -e ansible_become_pass=jhipster -e maven_version=3.6.3
        docker exec -t containertest mvn -version
    - name: NodeJS
      run: |
        docker exec -t containertest ansible-playbook node.yml -e ansible_become_pass=jhipster -e node_version=18.18.0
        docker exec -t containertest node -v
        docker exec -t containertest npm -v
    - name: docker
      run: |
        docker exec -t containertest ansible-playbook docker.yml -e ansible_become_pass=jhipster -u jhipster
        docker exec -t containertest docker -v
        docker exec -t containertest groups jhipster
    - name: docker-compose
      run: |
        docker exec -t containertest ansible-playbook dockercompose.yml -e ansible_become_pass=jhipster -e docker_compose_version=2.5.1
        docker exec -t containertest docker-compose version
    - name: fusuma
      run: |
        docker exec -t containertest ansible-playbook fusuma.yml -e ansible_become_pass=jhipster
        docker exec -t containertest fusuma --version
